[package]
name = "actix-gcd" 
version = "0.1.0" 
authors = ["AMD <michojekunle1@gmail.com>"]
edition = "2024" 

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html 

[dependencies]
actix-web = "4" 
serde = { version = "1.0", features = ["derive"] }